[project]
name = "eec"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langchain>=1.2.8",
    "langchain-core>=0.3.0",
    "langchain-groq>=1.1.2",
    "pydantic>=2.0.0",
    "python-dotenv>=1.2.1",
]
